version = 0.1
[engagex]
[engagex.deploy]
[engagex.deploy.parameters]
stack_name = "patientcheckout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b2istqwutmba"
s3_prefix = "patientcheckout"
region = "eu-west-1"
profile = "engagex"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patientcheckout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hg2ixn8wti0p"
s3_prefix = "patientcheckout"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
